apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: orchestrator-gateway
  namespace: {{ .Values.Namespace }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: orchestrator-virtualservice
  namespace: {{ .Values.Namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - orchestrator-gateway
  http:
  - match:
    - uri:
        prefix: /api/v1/
    route:
    - destination:
        host: orchestrator
        port:
          number: 8080
  # Add additional match and route blocks for the other paths
