apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: {{ .Values.Namespace }}
spec:
  selector:
    app: orchestrator
  ports:
    - name: api
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30010
  type: NodePort
