# orchestrator deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-enforcer
  namespace: {{ .Values.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-enforcer
  template:
    metadata:
      labels:
        app: policy-enforcer
    spec:
      containers:
      - name: policy-enforcer
        image: jorrit05/dynamos-policy-enforcer:0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: OC_AGENT_HOST
          value: {{ .Values.tracingEndpoint }}
        # resources:
        #   requests:
        #     memory: "128Mi"
        #   limits:
        #     memory: "256Mi"

      - name: sidecar
        image: jorrit05/dynamos-sidecar:0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: AMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbit
              key: password
        - name: AMQ_USER
          value: normal_user
        - name: OC_AGENT_HOST
          value: {{ .Values.tracingEndpoint }}
