# orchestrator deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-enforcer
  namespace: {{ .Values.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-enforcer
  template:
    metadata:
      labels:
        app: policy-enforcer
    spec:
      containers:
      - name: policy-enforcer
        image: policy_enforcer:latest
        imagePullPolicy: Always
        # resources:
        #   requests:
        #     memory: "128Mi"
        #   limits:
        #     memory: "256Mi"

      - name: rabbitmq-sidecar
        image: rabbitmq-sidecar:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3005
        env:
        - name: RABBIT_DNS
          value: rabbitmq.core.svc.cluster.local
        - name: AMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbit
              key: password
        - name: AMQ_USER
          value: normal_user
