apiVersion: v1
kind: Service
metadata:
  name: reasoner
  namespace: {{ .Values.Namespace }}
spec:
  selector:
    app: reasoner
  ports:
    - name: api
      protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30011
  type: NodePort
