# reasoner deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reasoner
  namespace: {{ .Values.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reasoner
  template:
    metadata:
      labels:
        app: reasoner
    spec:
      containers:
      - name: reasoner
        image: reasoner_service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        env:
        - name: ETCD_ENDPOINTS
          value: {{ .Values.etcdEndpoints }}
        - name: AMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbit
              key: password
        - name: AMQ_USER
          value: normal_user
        volumeMounts:
        - name: service-logs
          mountPath: /var/log/service_logs
        - name: stack-files
          mountPath: /var/log/stack-files
        # resources:
        #   requests:
        #     memory: "128Mi"
        #   limits:
        #     memory: "256Mi"
      volumes:
      - name: service-logs
        hostPath:
          path: /Users/jorrit/Documents/master-software-engineering/thesis/micro-recomposer/logs
      - name: stack-files
        hostPath:
          path: /Users/jorrit/Documents/master-software-engineering/thesis/micro-recomposer/stack/
