apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: core
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: core
spec:
  selector:
    app: adminer
  ports:
    - name: adminer
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002
  type: NodePort
