# debug-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: core
spec:
  containers:
  - name: debug
    image: busybox
    command: ['sleep', '3600']
    stdin: true
    tty: true
