apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: core
spec:
  ports:
  - port: 2379
    name: client
    nodePort: 30005
    targetPort: 2379
  - port: 2380
    name: peer
    targetPort: 2380
  selector:
    app: etcd
  type: NodePort


---

apiVersion: v1
kind: Service
metadata:
  name: etcd-headless
  namespace: {{ .Values.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
spec:
  ports:
  - port: 2379
    name: client
  - port: 2380
    name: peer
  clusterIP: None
  selector:
    app: etcd
