apiVersion: v1
kind: Namespace
metadata:
  name: core
  annotations:
    "helm.sh/resource-policy": keep
    "app.kubernetes.io/managed-by": "Helm"
    "linkerd.io/inject" : enabled
    # "config.linkerd.io/trace-collector": collector.linkerd-jaeger:14268


---

apiVersion: v1
kind: Namespace
metadata:
  name:  orchestrator
  annotations:
    "helm.sh/resource-policy": keep
    "linkerd.io/inject" : enabled
    "config.linkerd.io/trace-collector": collector.linkerd-jaeger:55678 # or 14268?

---

apiVersion: v1
kind: Namespace
metadata:
  name: uva
  annotations:
    "helm.sh/resource-policy": keep
    "app.kubernetes.io/managed-by": "Helm"

---

apiVersion: v1
kind: Namespace
metadata:
  name: vu
  annotations:
    "helm.sh/resource-policy": keep
    "app.kubernetes.io/managed-by": "Helm"

---

apiVersion: v1
kind: Namespace
metadata:
  name: surf
  annotations:
    "helm.sh/resource-policy": keep
    "app.kubernetes.io/managed-by": "Helm"

