apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbit-pvc
  namespace: core
  annotations:
    "linkerd.io/inject" : disabled
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
