# Define Persistent Volume (PV) explicitely on the node, otherwise, the PVC cannot find it. This did work without PV on the local setup, but for the FABRIC this was required.
# https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1/
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbit-pv
spec:
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # local path on node (has pv at the end to avoid conflict with rabbit-data in core chart PV for rabbit-data-pvc)
    path: "/mnt/rabbit-pv"
  persistentVolumeReclaimPolicy: Retain
  # Use the dynamos-core node for this
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.node }}
---
# https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-claim-v1/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbit-pvc
  namespace: core
  annotations:
    "linkerd.io/inject": disabled
spec:
  # binds to the PV above
  volumeName: rabbit-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
