# # Configuration file for prometheus (keep this format, as this has been configured to update the prometheus configuration file, otherwise it will not work!)
apiVersion: v1
kind: ConfigMap
metadata:
 name: prometheus-server
data:
 prometheus.yml: |
  global:
  scrape_configs:
   - job_name: 'kubernetes-kubelet'
     scheme: https
     tls_config:
       ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
       insecure_skip_verify: true
     bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
     kubernetes_sd_configs:
     - role: node
     relabel_configs:
     - action: labelmap
       regex: __meta_kubernetes_node_label_(.+)
     - target_label: __address__
       replacement: kubernetes.default.svc.cluster.local:443
     - source_labels: [__meta_kubernetes_node_name]
       regex: (.+)
       target_label: __metrics_path__
       replacement: /api/v1/nodes/${1}/proxy/metrics
   - job_name: 'kubernetes-cadvisor'
     scheme: https
     tls_config:
       ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
       insecure_skip_verify: true
     bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
     kubernetes_sd_configs:
     - role: node
     relabel_configs:
     - action: labelmap
       regex: __meta_kubernetes_node_label_(.+)
     - target_label: __address__
       replacement: kubernetes.default.svc.cluster.local:443
     - source_labels: [__meta_kubernetes_node_name]
       regex: (.+)
       target_label: __metrics_path__
       replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
   - job_name: 'kubernetes-kube-state'
     kubernetes_sd_configs:
     - role: pod
     relabel_configs:
     - action: labelmap
       regex: __meta_kubernetes_pod_label_(.+)
     - source_labels: [__meta_kubernetes_namespace]
       action: replace
       target_label: kubernetes_namespace
     - source_labels: [__meta_kubernetes_pod_name]
       action: replace
       target_label: kubernetes_pod_name
     - source_labels: [__meta_kubernetes_pod_label_grafanak8sapp]
       regex: .*true.*
       action: keep
     - source_labels: ['__meta_kubernetes_pod_label_daemon', '__meta_kubernetes_pod_node_name']
       regex: 'node-exporter;(.*)'
       action: replace
       target_label: nodename

  #  - job_name: 'rabbitmq'
  #    tls_config:
  #      insecure_skip_verify: true
  #      metrics_path: '/metrics'
  #     scrape_interval: 5s
  #     static_configs:
  #       - targets: ['rabbitmq.core.svc.cluster.local:15692']
  #     basic_auth:
  #       username: 'guest'
  #       password: 'guest'



# # Also, do NOT rename this file, because this way it needs to be this name to be able to update the prometheus configuration file exactly like this file content.
# global:
#   evaluation_interval: 1m
#   scrape_interval: 1m
#   scrape_timeout: 10s

# scrape_configs:
# - job_name: 'prometheus'
#   static_configs:
#     - targets: ['localhost:9090']

# - job_name: 'kubelet'
#   scheme: https
#   tls_config:
#     insecure_skip_verify: true
#   bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
#   scrape_interval: 5s
#   kubernetes_sd_configs:
#     - role: node
#   relabel_configs:
#     - action: labelmap
#       regex: __meta_kubernetes_node_label_(.+)
#     - target_label: __address__
#       replacement: kubernetes.default.svc:443
#     - source_labels: [__address__]
#       target_label: __metrics_path__
#       replacement: /metrics

# - job_name: 'kube-state-metrics'
#   static_configs:
#     - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']

# - job_name: node-exporter
#   metrics_path: metrics
#   static_configs:
#     - targets: ['nodeexporter:9100']

# - job_name: cadvisor
#   metrics_path: metrics
#   scrape_interval: 10s
#   static_configs:
#     - targets: ['cadvisor:8080']

# - job_name: 'kubernetes-nodes-cadvisor'
#   scheme: https
#   tls_config:
#     ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
#   bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
#   kubernetes_sd_configs:
#     - role: node
#   relabel_configs:
#   - action: labelmap
#     regex: __meta_kubernetes_node_label_(.+)
#   - target_label: __address__
#     replacement: kubernetes.default.svc:443
#   - source_labels: [__meta_kubernetes_node_name]
#     target_label: __metrics_path__
#     replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
#   - source_labels: [__meta_kubernetes_namespace]
#     target_label: namespace
#   - source_labels: [__meta_kubernetes_pod_name]
#     target_label: pod
#   - source_labels: [__meta_kubernetes_pod_container_name]
#     target_label: container

# - job_name: 'rabbitmq'
#   tls_config:
#     insecure_skip_verify: true
#   metrics_path: '/metrics'
#   scrape_interval: 5s
#   static_configs:
#     - targets: ['rabbitmq.core.svc.cluster.local:15692']
#   basic_auth:
#     username: 'guest'
#     password: 'guest'