global:
  scrape_interval: 1m
  evaluation_interval: 1m
  scrape_timeout: 25s

scrape_configs:
  - job_name: 'cadvisor'
    # Configures Kubernetes service discovery to find pods
    kubernetes_sd_configs:
      - role: pod
    # Configures relabeling rules
    relabel_configs:
      # Keep only pods with the label app=cadvisor (otherwise all other metrics will be included, but you only want cadvisor metrics)
      - source_labels: [__meta_kubernetes_pod_label_name]
        action: keep
        regex: cadvisor
      # Replace target with pod IP and port 8080 (where cadvisor runs)
      - source_labels: [__meta_kubernetes_pod_ip]
        action: replace
        target_label: __address__
        regex: (.+)
        replacement: ${1}:8080
      # Replace container_label_io_kubernetes_container_name with container_name (e.g. container_label_io_kubernetes_container_name="linkerd-proxy")
      # This allows to use the container_name label in queries and easily find containers
      - source_labels: [container_label_io_kubernetes_container_name]
        target_label: container_name