serverFiles:
  prometheus.yml:
    global:
      evaluation_interval: 1m
      scrape_interval: 1m
      scrape_timeout: 10s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'kubelet'
        scheme: https
        tls_config:
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        scrape_interval: 5s
        kubernetes_sd_configs:
        - role: node
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__address__]
          target_label: __metrics_path__
          replacement: /metrics

      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
      # cadvisor for container metrics (CPU, memory, etc.)
      - job_name: 'kubernetes-cadvisor'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
        - role: node
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

      - job_name: 'rabbitmq'
        tls_config:
          insecure_skip_verify: true
        metrics_path: '/metrics'
        scrape_interval: 5s
        static_configs:
          - targets: ['rabbitmq.core.svc.cluster.local:15692']
        basic_auth:
          username: 'guest'
          password: 'guest'

# # Disable grafana (not used currently)
# grafana:
#   enabled: false

# Old solution (original file from DYNAMOS, keep for going back to this)
# extraScrapeConfigs: |
#   - job_name: 'kubelet'
#     scheme: https
#     tls_config:
#       insecure_skip_verify: true
#     bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
#     scrape_interval: 5s
#     kubernetes_sd_configs:
#     - role: node
#     relabel_configs:
#     - action: labelmap
#       regex: __meta_kubernetes_node_label_(.+)
#     - target_label: __address__
#       replacement: kubernetes.default.svc:443
#     - source_labels: [__address__]
#       target_label: __metrics_path__
#       replacement: /metrics

#   # - job_name: 'kubelet'
#   #   scheme: https
#   #   tls_config:
#   #     insecure_skip_verify: true
#   #   bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
#   #   kubernetes_sd_configs:
#   #   - role: node
#   #   relabel_configs:
#   #   - action: labelmap
#   #     regex: __meta_kubernetes_node_label_(.+)
#   #   - target_label: __address__
#   #     replacement: kubernetes.default.svc:443
#   #   - source_labels: [__meta_kubernetes_node_name]
#   #     regex: (.+)
#   #     target_label: __metrics_path__
#   #     replacement: /api/v1/nodes/${1}/proxy/metrics
#  - job_name: 'rabbitmq'
#    tls_config:
#      insecure_skip_verify: true
#    metrics_path: '/metrics'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['rabbitmq.core.svc.cluster.local:15692']
#    basic_auth:
#      username: 'guest'
#      password: 'guest'



# # server:
# #   podAnnotations:
# #     config.linkerd.io/skip-outbound-ports: "15692"