Namespace: core

dns:
  loki: loki.core.svc.cluster.local

db:
  image: mysql
  resources:
    reservations:
      memory: 128Mi
    limits:
      memory: 256Mi
  env:
    MYSQL_USER: jorrit
    MYSQL_DATABASE: mydb

adminer:
  image: adminer
  ports:
    - 8085:8080

rabbitmq:
  image: rabbitmq:3-management
  ports:
    - 5672:5672
    - 15672:15672
  env:
    RABBITMQ_ERLANG_COOKIE: "mysecretcookie"
    RABBITMQ_DEFAULT_USER: "guest"
    RABBITMQ_DEFAULT_PASS: "guest"
    RABBITMQ_LOGS: "-"

volumes:
  data:
    hostPath: "/Users/jorrit/.docker-conf/rabbitmq/data/"
  log:
    hostPath: "/Users/jorrit/.docker-conf/rabbitmq/log/"
  config:
    hostPath: "/Users/jorrit/Documents/master-software-engineering/thesis/DYNAMOS/stack/config/rabbitmq.conf"
  definitions:
    hostPath: "/Users/jorrit/Documents/master-software-engineering/thesis/DYNAMOS/stack/config/definitions.json"
  docker:
    hostPath: "/var/run/docker.sock"
  mysql:
    hostPath: "/Users/jorrit/Documents/mysql"

etcd:
  nodeName: 0
  replicaCount: 3
  image:
    repository: quay.io/coreos/etcd
    tag: v3.5.1
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP


loki:
  image: grafana/loki:2.8.0
  ports:
    - "3100:3100"

promtail:
  image: grafana/promtail:2.8.0

grafana:
  image: grafana/grafana:latest
  ports:
    - 3000:3000

networks:
  core_network:
    external: true
  unl_1:
    external: true
  unl_2:
    external: true
  third_party:
    external: true

secrets:
  db_root_password:
    external: true
  db_dba_password:
    external: true
  rabbitmq_user:
    external: true
