version: '3.9'

services:

  # zipkin:
  #   image: openzipkin/zipkin:2.24.0
  #   ports:
  #     - 9411:9411
  #   networks:
  #     core_network:
  #       aliases:
  #         - zipkin

  loki:
    image: grafana/loki:2.8.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      core_network:
        aliases:
          - loki

  promtail:
    image: grafana/promtail:2.8.0
    volumes:
      - service_logs:/var/log/service_logs
      - ./config/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      core_network:
        aliases:
          - promtail

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/:/etc/grafana/provisioning/dashboards
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        # mkdir -p /etc/grafana/provisioning/dashboards
        cat <<EOF > /etc/grafana/provisioning/dashboards/dashboards.yaml
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          updateIntervalSeconds: 300
          options:
            path: /etc/grafana/provisioning/dashboards
        EOF
        /run.sh
    networks:
      core_network:
        aliases:
          - grafana

networks:
  core_network:
    external: true
  unl_1:
    external: true
  unl_2:
    external: true
  third_party:
    external: true

volumes:
  service_logs:
    external: true

secrets:
  db_root_password:
    external: true
  db_dba_password:
    external: true
  rabbitmq_user:
    external: true

