apiVersion: apps/v1
kind: Deployment
metadata:
  name: anonymize-service
  labels:
    app: anonymize-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anonymize-service
  template:
    metadata:
      labels:
        app: anonymize-service
    spec:
      containers:
      - name: anonymize-service
        image: anonymize_service
        volumeMounts:
        - name: service-logs
          mountPath: /var/log/service_logs
        env:
        - name: INPUT_QUEUE
          value: query_service
        - name: AMQ_PASSWORD_FILE
          value: /run/secrets/rabbitmq_user
        - name: AMQ_USER
          value: normal_user
      volumes:
      - name: service-logs
        persistentVolumeClaim:
          claimName: service-logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: anonymize-service
spec:
  selector:
    app: anonymize-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-service
  labels:
    app: query-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query-service
  template:
    metadata:
      labels:
        app: query-service
    spec:
      containers:
      - name: query-service
        image: query_service
        volumeMounts:
        - name: service-logs
          mountPath: /var/log/service_logs
        env:
        - name: MYSQL_ROOT_PASSWORD_FILE
          value: /run/secrets/db_root_password
        - name: MYSQL_PASSWORD_FILE
          value: /run/secrets/db_dba_password
        - name: MYSQL_DATABASE
          value: mydb
        - name: DB_USER
          value: root
        - name: INPUT_QUEUE
          value: gateway_service
        - name: AMQ_PASSWORD_FILE
          value: /run/secrets/rabbitmq_user
        - name: AMQ_USER
          value: normal_user
      volumes:
      - name: service-logs
        persistentVolumeClaim:
          claimName: service-logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: query-service
spec:
  selector:
    app: query-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
