apiVersion: v1
kind: Secret
metadata:
  name: my-minio-cred
  namespace: argo
type: Opaque
data:
  accesskey: Z3Vlc3Q=
  secretkey: c3VwZXJndWVzdA==

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argo
  name: argo-workflows
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflows
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflows
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo


