Namespace: api-gateway
etcdDns: etcd-headless.core.svc.cluster.local
tracingEndpoint: collector.linkerd-jaeger:55678
branchNameTag: "api-gateway-archetypes-test"
dockerArtifactAccount: "poetoec"
# Default DYNAMOS (old):
# branchNameTag: "main"
# dockerArtifactAccount: "dynamos1"

# Use the dynamos-core node for this
node: dynamos-core