# apiVersion: networking.istio.io/v1beta1
# kind: VirtualService
# metadata:
#   name: grafana-virtualservice
#   namespace: {{ .Values.Namespace }}
# spec:
#   hosts:
#   - "*"
#   gateways:
#   - {{ .Values.Namespace }}/core-gateway
#   http:
#   - match:
#     - uri:
#         prefix: /grafana
#     route:
#     - destination:
#         host: grafana.core.svc.cluster.local
#         port:
#           number: 3000
