# TODO: test and/or change if necessary to allow grafana
loki:
  image: grafana/loki:2.8.0
  port: "3100"

promtail:
  image: grafana/promtail:2.8.0

grafana:
  image: grafana/grafana:latest
  ports:
    - 3000:3000