# debug-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: {{ .Values.Namespace }}
spec:
  # Use the DYNAMOS core node for this, see https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors
  nodeSelector:
    kubernetes.io/hostname: {{ .Values.node }}
  containers:
  - name: debug
    image: busybox
    command: ['sleep', '3600']
    stdin: true
    tty: true
# # debug-service.yaml
# apiVersion: v1
# kind: Service
# metadata:
#   name: debug-service
#   namespace: customer-centerdemo
# spec:
#   type: ClusterIP
#   selector:
#     name: debug
#   ports:
#   - protocol: TCP, ICMP
#     port: 80
#     targetPort: 80 # Or whichever port your application in the debug pod is running on
