apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: core
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 30020
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 30000
    - name: metrics
      protocol: TCP
      port: 15692
      targetPort: 15692
  type: NodePort

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data-pvc
  namespace: core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-log-pvc
  namespace: core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: Service
metadata:
  name: "rabbitmq-clusterip"
  namespace: core
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672

---

apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: core
type: Opaque
stringData:
  rabbitmq-user: "{{ .Values.rabbitmq.env.RABBITMQ_DEFAULT_USER }}"
  rabbitmq-password: "{{ .Values.rabbitmq.env.RABBITMQ_DEFAULT_PASS }}"
