# charts/mychart/templates/cadvisor-service-monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cadvisor
  namespace: kube-system
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      k8s-app: cadvisor
  endpoints:
  - port: http
    interval: {{ .Values.cadvisor.monitor.interval }}
