apiVersion: apps/v1
kind: Deployment
metadata:
  name: unl1-agent
  labels:
    app: unl1-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unl1-agent
  template:
    metadata:
      labels:
        app: unl1-agent
    spec:
      containers:
      - name: unl1-agent
        image: agent_service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: ETCD_ENDPOINTS
          value: {{ .Values.etcdEndpoints}}
        - name: RABBIT_DNS
          value: {{ .Values.rabbitDns }}
        - name: AMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbit
              key: password
        - name: AMQ_USER
          value: normal_user
        - name: CONTAINER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: service-logs
          mountPath: /var/log/service_logs
        - name: stack-files
          mountPath: /var/log/stack-files
      volumes:
      - name: service-logs
        hostPath:
          path: /Users/jorrit/Documents/master-software-engineering/thesis/DYNAMOS/logs
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: stack-files
        hostPath:
          path: /Users/jorrit/Documents/master-software-engineering/thesis/DYNAMOS/stack/
