apiVersion: apps/v1
kind: Deployment
metadata:
  name: uva
  namespace: uva
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uva
  template:
    metadata:
      labels:
        app: uva
    spec:
      serviceAccountName: job-creator-uva
      containers:
      - name: uva
        image: agent:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DATA_STEWARD_NAME
          value: UVA
        # resources:
        #   requests:
        #     memory: "128Mi"
        #   limits:
        #     memory: "256Mi"
      - name: sidecar
        image: sidecar:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3005
        env:
        - name: AMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbit
              key: password
        - name: AMQ_USER
          value: normal_user

