apiVersion: apps/v1
kind: Deployment
metadata:
  name: vu
  namespace: vu
spec:
  replicas: 0
  selector:
    matchLabels:
      app: vu
  template:
    metadata:
      labels:
        app: vu
    spec:
      containers:
      - name: vu
        image: agent:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DATA_STEWARD_NAME
          value: VU
        # resources:
        #   requests:
        #     memory: "128Mi"
        #   limits:
        #     memory: "256Mi"
      - name: rabbitmq-sidecar
        image: rabbitmq-sidecar:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3005
        env:
        - name: AMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbit
              key: password
        - name: AMQ_USER
          value: normal_user